version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - '5555:8888'
    container_name: datascience_app
    volumes:
      - '.:/work'
    tty: true
    stdin_open: true
